In [4]:
#!pip install tensorflow

  Running setup.py bdist_wheel for termcolor: started
  Running setup.py bdist_wheel for termcolor: finished with status 'done'
  Stored in directory: C:\Users\Ananya\AppData\Local\pip\Cache\wheels\7c\06\54\bc84598ba1daf8f970247f550b175aaaee85f68b4b0c5ab2c6
  Running setup.py bdist_wheel for absl-py: started
  Running setup.py bdist_wheel for absl-py: finished with status 'done'
  Stored in directory: C:\Users\Ananya\AppData\Local\pip\Cache\wheels\90\db\f8\2c3101f72ef1ad434e4662853174126ce30201a3e163dcbeca
  Running setup.py bdist_wheel for gast: started
  Running setup.py bdist_wheel for gast: finished with status 'done'
  Stored in directory: C:\Users\Ananya\AppData\Local\pip\Cache\wheels\5c\2e\7e\a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd
Successfully built termcolor absl-py gast


distributed 1.21.8 requires msgpack, which is not installed.
You are using pip version 10.0.1, however version 19.0.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [13]:
import tensorflow as tf

In [14]:
#constant is a variable type in tensorflow
hello = tf.constant("helloworld")
hello

<tf.Tensor 'Const_3:0' shape=() dtype=string>

In [15]:
#Variable type in tensorflow
state = tf.Variable(0)

In [16]:
one  = tf.constant(1)

In [17]:
new_value = tf.add(state,one)

In [22]:
#this statement will through error bcz one is a constant so it can't be updated
#update = tf.assign(one,new_value)

In [21]:
update = tf.assign(state,new_value) # state is varianle so it can be changed

In [23]:
init_op = tf.global_variables_initializer()

In [24]:
#session is used to start execution 
sess = tf.Session()

In [25]:
sess.run(init_op)

In [26]:
print(sess.run(update))

1


In [35]:
#placeholder is another type of variable
a = tf.placeholder(tf.float32)

In [36]:
a

<tf.Tensor 'Placeholder_1:0' shape=<unknown> dtype=float32>

In [37]:
b = a*2

In [34]:
sess.run(b,feed_dict = {a:3.0}) # feeding placeholder

6.0

In [40]:
#another way of feeding, instead of doing hardcoding we can give the variable dictionary
dictionary = {a:[[1,2,3],[4,5,6],[7,8,9],[10,12,13],[14,15,16],[17,18,19],[20,21,22],[23,24,25]]}

In [41]:
result = sess.run(b,feed_dict = dictionary)
print(result)

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]
 [20. 24. 26.]
 [28. 30. 32.]
 [34. 36. 38.]
 [40. 42. 44.]
 [46. 48. 50.]]


In [43]:
#here w are closing the session
sess.close()

In [51]:
#here we r giving init_op because update is having variable
with tf.Session() as sess:
  result = sess.run(b,feed_dict = {a:3.5})
  sess.run(init_op)
  sess.run(update)
  
  print(result)

7.0


In [52]:
with tf.Session() as sess:
  result = sess.run(b,feed_dict = dictionary)
  print(result)

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]
 [20. 24. 26.]
 [28. 30. 32.]
 [34. 36. 38.]
 [40. 42. 44.]
 [46. 48. 50.]]


### In case of two place holders

In [55]:
a = tf.placeholder(tf.float32)

In [56]:
b = tf.placeholder(tf.float32)

In [57]:
c = a+b

In [58]:
sess = tf.Session()

In [59]:
result = sess.run(c,feed_dict = {a:10,b:20})

In [60]:
print(result)

30.0


In [61]:
d = a*c

In [62]:
result = sess.run(d,feed_dict = {a:10,b:20})

In [63]:
print(result)

300.0


In [64]:
avalues = [1,2,3]
bvalues = [4,5,6]

In [65]:
result = sess.run(c,feed_dict = {a:avalues,b:bvalues})

In [66]:
print(result)

[5. 7. 9.]


In [69]:
result = sess.run(d,feed_dict = {a:avalues,b:bvalues})

In [70]:
print(result)

[ 5. 14. 27.]
